#!/usr/bin/python3
# -*- coding:utf-8 -*-

import os
import time
import shutil
import Lpnet
import angle_num
import filter_process
import snps
import subprocess
import get_filename
from alignment import fasta_select
import numpy as np
import itertools
from Bio import Phylo
import sys
import json
import csv


recursion_limit = os.environ.get("AUGUR_RECURSION_LIMIT")
if recursion_limit:
	sys.setrecursionlimit(int(recursion_limit))
else:
	sys.setrecursionlimit(10000)

def write_log(locus, log_text):
	logfile = get_filename.logfile(locus)
	with open(logfile, 'a') as f:
		f.write(log_text)

def make_tree(fasta, tree_out, method, threads):
	if method == "RAxML":
		cmd = [
			"raxml-ng",
			"--msa", fasta,
			"--all",
			"--model", "GTR+G",
			"--bs-trees", "100",
			"--prefix", tree_out,
			"--redo",
			"--seed", "1",
			"--threads", str(threads)
		]
		subprocess.run(cmd, check=True, text=True)
		return tree_out + ".raxml.support"

	if method == "FastTree":
		tree_file = tree_out + ".tre"
		with open(tree_file, "w") as out_handle:
			subprocess.run(
				["FastTree", "-gtr", "-nt", "-seed", "1234", fasta],
				stdout=out_handle,
				check=True,
				text=True
			)
		return tree_file

	raise ValueError(f"Unknown tree method: {method}")

def dismat_generate(tree_file, dmcsv, dmlist):
	tree = Phylo.read(tree_file, 'newick')

	node_list = []

	for node in tree.get_terminals():
		node_list.append(node.name)

	with open(dmlist, 'w') as f:
		for item in node_list:
			f.write(item + '\n')
   	     

	ret_val = tree.get_terminals()
	num_node = tree.count_terminals()
	distance_ndarray = np.zeros((num_node, num_node))

	for combi in itertools.combinations(range(num_node), 2):  # Make distance matrix
		dist_temp = tree.distance(ret_val[combi[0]], ret_val[combi[1]])
		distance_ndarray[combi[0], combi[1]] = dist_temp
		distance_ndarray[combi[1], combi[0]] = dist_temp
	
	np.savetxt(dmcsv, distance_ndarray, delimiter=',')

def make_distance_matrix(locus, fasta, method, threads):
	write_log(locus, f"make_distance_matrix_from_selected_seq\tBegin\t{str(time.ctime())}\n")
	directory_path = get_filename.dir_path(locus)
	tree_dir = get_filename.tree_dir(locus)
	
	# Make a tree with blast selected alleles "selected_align"
	tree_out = tree_dir + f"/{locus}"
	tree_file = make_tree(fasta, tree_out, method, threads)

	dmcsv = directory_path + f"/{locus}_dm.csv"
	dmlist = directory_path + f"/{locus}_dm.list"
	dismat_generate(tree_file , dmcsv, dmlist) ######### dismat_generate() ########
	write_log(locus, f"make_distance_matrix_from_selected_seq\tEnd\t{str(time.ctime())}\n")

def save_medoid_assignment(locus, medoid_list, medoid_assignment):
	directory_path = get_filename.dir_path(locus)
	out_json = os.path.join(directory_path, f"{locus}_medoid_assignment.json")
	out_list = os.path.join(directory_path, f"{locus}_medoid.list")

	with open(out_json, "w") as f:
		json.dump(medoid_assignment, f, indent=2)

	with open(out_list, "w") as f:
		for medoid in medoid_list:
			f.write(medoid + "\n")

def run_lpnet(locus, group, max_lpnet_taxa):
	# determine the order of alleles on a circle
	directory_path = get_filename.dir_path(locus)
	dmcsv = directory_path + f"/{locus}_dm.csv"
	dmlist = directory_path + f"/{locus}_dm.list"
	outnex = directory_path + f"/{locus}.nex"
	circleList_file = directory_path + f"/{locus}_circle.list"

	if group == 'group1' or group == 'group3':
		Lpnet.lpnet(dmcsv, dmlist, outnex)
		label_list, medoid_list, medoid_assignment = [], [], {}

		# For group1 and group3, lpnet input labels are all labels in dmlist.
		with open(dmlist, "r") as f:
			expected_labels = [line.strip() for line in f if line.strip()]

	else:  # group == 'group2' or group == 'group4'
		label_list, medoid_list, medoid_assignment = Lpnet.medoid_lpnet(
			dmcsv,
			dmlist,
			outnex,
			max_lpnet_taxa
		)

		# For group2 and group4, lpnet input labels are medoids only.
		expected_labels = medoid_list

	# Extract allele names from the Nexus file generated by lpnet.
	with open(outnex, 'r') as f:
		lines = f.readlines()

	filtered_lines = []
	for line in lines:
		if locus in line:
			parts = line.split("'")
			if len(parts) > 1:
				filtered_lines.append(parts[1])

	# Keep order, remove duplicates, and retain only expected labels.
	expected_set = set(expected_labels)
	cleaned = []
	seen = set()

	for x in filtered_lines:
		if x in expected_set and x not in seen:
			cleaned.append(x)
			seen.add(x)

	if not cleaned:
		raise ValueError(f"No allele order was extracted from lpnet output: {outnex}")

	missing = expected_set - set(cleaned)
	if missing:
		raise ValueError(
			f"{len(missing)} lpnet input alleles were not found in lpnet order. "
			f"Examples: {list(missing)[:5]}"
		)

	extra = set(filtered_lines) - expected_set
	if extra:
		write_log(
			locus,
			f"Warning\tignored_unexpected_lpnet_labels={len(extra)}\t"
			f"examples={list(extra)[:5]}\n"
		)

	with open(circleList_file, 'w') as f_out:
		for x in cleaned:
			f_out.write(x + '\n')

	if group not in ("group1", "group3"):
		save_medoid_assignment(locus, medoid_list, medoid_assignment)

	return label_list, medoid_list, medoid_assignment

def dismat4group(locus, mode, method, threads):

	# Preparing files and directories
	directory_path = get_filename.dir_path(locus)
	selected_align = get_filename.selected_align(locus)
	if mode == 'Mid':
		list_dir = directory_path + "/Mid_list"
		fasta_dir = directory_path + "/Mid_align"
		sub_tree_dir = directory_path + "/Mid_tree"
		sub_dm_dir = directory_path + "/Mid_dismat"
		sub_dmlist_dir = directory_path + "/Mid_dmlist"
	else:
		list_dir = directory_path + "/End_list"
		fasta_dir = directory_path + "/End_align"
		sub_tree_dir = directory_path + "/End_tree"
		sub_dm_dir = directory_path + "/End_dismat"
		sub_dmlist_dir = directory_path + "/End_dmlist"

	os.makedirs(sub_tree_dir, exist_ok=True)
	os.makedirs(sub_dm_dir, exist_ok=True)
	os.makedirs(sub_dmlist_dir, exist_ok=True)

	# Get group list in /End_list
	lsfile_list = os.listdir(list_dir)
	
	# make fasta for each group
	for filename in lsfile_list:
		# generate full path
		file_path = os.path.join(list_dir, filename)
		listfile_name = os.path.basename(filename)
		allele_name = os.path.splitext(listfile_name)[0]
		fastaout = fasta_dir + f"/{allele_name}.aln"
		listfile_path = list_dir + "/" + filename
		fasta_select(selected_align, fastaout, listfile_path)
	
	# Get file name in fasta directory containing fasta files for each group
	fsfile_list = os.listdir(fasta_dir)		
	for filename in fsfile_list:			
		# Make tree for each group
		fasta_path = os.path.join(fasta_dir, filename)
		fastafile_name = os.path.basename(filename)
		allele_name = os.path.splitext(fastafile_name)[0]
		outfile = sub_tree_dir + f"/{allele_name}"
		tr_file = make_tree(fasta_path, outfile, method, threads) # Run phylogenetic tree calculation
		# Make distance matrix files (dismat) for each group
		sub_dmcsv = sub_dm_dir + f"/{allele_name}_dm.csv"
		sub_dmlist = sub_dmlist_dir + f"/{allele_name}_dm.list"
		write_log(locus, f"make_distance_matrix_from_{os.path.basename(tr_file)}\tBegin\t{str(time.ctime())}\n")
		dismat_generate(tr_file , sub_dmcsv, sub_dmlist)
		write_log(locus, f"make_distance_matrix_from_{os.path.basename(tr_file)}\tEnd\t{str(time.ctime())}\n")
		
	return(list_dir, fasta_dir, sub_tree_dir, sub_dm_dir, sub_dmlist_dir)

def prepare_files(locus):
	directory_path = get_filename.dir_path(locus)
	result_path = get_filename.result_path(locus)
	sdis_out = get_filename.sdis_out(locus)
	dmcsv = directory_path + f"/{locus}_dm.csv"
	dmlist = directory_path + f"/{locus}_dm.list"
	circleList_file = directory_path + f"/{locus}_circle.list"
	jsonfile = result_path + f"/{locus}.json"
	list_dir = directory_path + "/End_list"
	fasta_dir = directory_path + "/End_align"
	return(sdis_out, dmcsv, dmlist, circleList_file, jsonfile, list_dir, fasta_dir)

def group1(locus, method, threads):
	print("Group1")
	sdis_out, dmcsv, dmlist, circleList_file, jsonfile, list_dir, fasta_dir = prepare_files(locus)
	standard_allel = angle_num.G1_method(dmcsv, dmlist, circleList_file, jsonfile, locus)
	return(standard_allel)
		

def group2(locus, method, threads, label_list, medoid_list, medoid_assignment):
	print("Group2")
	sdis_out, dmcsv, dmlist, circleList_file, jsonfile, list_dir, fasta_dir = prepare_files(locus)
	os.makedirs(list_dir, exist_ok=True)
	os.makedirs(fasta_dir, exist_ok=True)
	
	filter_process.medoid_group_processing(
		circleList_file,
		list_dir,
		medoid_assignment
	)	
	list_dir, fasta_dir, sub_tree_dir, sub_dm_dir, sub_dmlist_dir = dismat4group(locus, 'normal', method, threads)
			
	standard_allel = angle_num.G2_method(dmcsv, dmlist, circleList_file, sub_dm_dir, sub_dmlist_dir, jsonfile, locus)
	return(standard_allel)
	

def group3(locus, selection, df_Sdis, key_list, method, threads):
	print("Group3")
	sdis_out, dmcsv, dmlist, circleList_file, jsonfile, list_dir, fasta_dir = prepare_files(locus)
	os.makedirs(list_dir, exist_ok=True)		
	os.makedirs(fasta_dir, exist_ok=True)

	snps.snpgroup_list(locus, circleList_file, list_dir, selection, df_Sdis, key_list)		
		
	list_dir, fasta_dir, sub_tree_dir, sub_dm_dir, sub_dmlist_dir = dismat4group(locus, 'normal', method, threads)

	standard_allel = angle_num.G3andG4_method(dmcsv, dmlist, circleList_file, sub_dm_dir, sub_dmlist_dir, jsonfile, locus, circleList_file)
	return(standard_allel)
	

def group4(locus, selection, df_Sdis, key_list, method, threads, label_list, medoid_list, medoid_assignment):
	print("Group4")

	write_log(locus, f"group4\tBegin\t{str(time.ctime())}\n")
	
	sdis_out, dmcsv, dmlist, circleList_file, jsonfile, list_dir, fasta_dir = prepare_files(locus)

	directory_path = get_filename.dir_path(locus)
	Mid_list_dir = directory_path + "/Mid_list"
	os.makedirs(Mid_list_dir, exist_ok=True)		
	Mid_fasta_dir = directory_path + "/Mid_align"
	os.makedirs(Mid_fasta_dir, exist_ok=True)
	Mid_dm_dir = directory_path + "/Mid_dismat"
	os.makedirs(Mid_dm_dir, exist_ok=True)
	Mid_dmlist_dir = directory_path + "/Mid_dmlist"
	os.makedirs(Mid_dmlist_dir, exist_ok=True)

	filter_process.medoid_group_processing(
		circleList_file,
		Mid_list_dir,
		medoid_assignment
	)
	list_dir, fasta_dir, sub_tree_dir, sub_dm_dir, sub_dmlist_dir = dismat4group(locus, 'Mid', method, threads)

	orderList_file = directory_path + f"/{locus}_order.list"
	angle_num.allorder_listmk(circleList_file, Mid_dm_dir, Mid_dmlist_dir, orderList_file)

	##### 2nd grouping #####
	list_dir = directory_path + "/End_list"
	os.makedirs(list_dir, exist_ok=True)		
	fasta_dir = directory_path + "/End_align"
	os.makedirs(fasta_dir, exist_ok=True)

	snps.snpgroup_list(locus, orderList_file, list_dir, selection, df_Sdis, key_list)
		
	list_dir, fasta_dir, sub_tree_dir, sub_dm_dir, sub_dmlist_dir = dismat4group(locus, 'normal', method, threads)

	standard_allel = angle_num.G3andG4_method(dmcsv, dmlist, orderList_file, sub_dm_dir, sub_dmlist_dir, jsonfile, locus, circleList_file)

	write_log(locus, f"group4\tEnd\t{str(time.ctime())}\n")

	return(standard_allel)
	


def del_tempfiles(locus):
	write_log(locus, f"Delete temporary files\t{str(time.ctime())}\n")
	directory_path = get_filename.dir_path(locus)

	selected_align = get_filename.selected_align(locus)
	selected_fasta = get_filename.selected_fasta(locus)
	sdis_out = get_filename.sdis_out(locus)
	ss_list = get_filename.ss_list(locus)
	dmcsv = directory_path + f"/{locus}_dm.csv"
	dmlist = directory_path + f"/{locus}_dm.list"
	circleList_file = directory_path + f"/{locus}_circle.list"
	orderList_file = directory_path + f"/{locus}_order.list"
	snp_select_fasta = directory_path + f"/{locus}ss.aln"
	file_list = [selected_align, 
				selected_fasta, 
				sdis_out, 
				ss_list, 
				dmcsv, 
				dmlist, 
				circleList_file, 
				orderList_file, 
				snp_select_fasta
				]
	for f in file_list:
		if os.path.isfile(f):
			os.remove(f)

	Init_tree_dir = directory_path + "/Init_tree"
	Mid_list_dir = directory_path + "/Mid_list"
	Mid_fasta_dir = directory_path + "/Mid_align"
	Mid_dm_dir = directory_path + "/Mid_dismat"
	Mid_dmlist_dir = directory_path + "/Mid_dmlist"
	Mid_tree_dir = directory_path + "/Mid_tree"
	END_list_dir = directory_path + "/End_list"
	END_fasta_dir = directory_path + "/End_align"
	END_dm_dir = directory_path + "/End_dismat"
	END_dmlist_dir = directory_path + "/End_dmlist"
	END_tree_dir = directory_path + "/End_tree"
	dir_list = [
				Init_tree_dir,
				Mid_list_dir,
				Mid_fasta_dir,
				Mid_dm_dir,
				Mid_dmlist_dir,
				Mid_tree_dir,
				END_list_dir,
				END_fasta_dir,
				END_dm_dir,
				END_dmlist_dir,
				END_tree_dir
				]
	for d in dir_list:
		if os.path.isdir(d):
			shutil.rmtree(d)

def get_group(locus):
	ss_list = get_filename.ss_list(locus)
	with open(ss_list, 'r') as file:
		my_list = file.readlines()
	# get the length of the list
	list_length = len(my_list)

	hit_list = get_filename.hit_list(locus)
	with open(hit_list, 'r') as file:
		alleles_list = file.readlines()
	num_alleles = len(alleles_list)

	# Make phyloCode database
	if list_length < 5:
		if num_alleles <= 80:
			group = 'group1'
		else:
			group = 'group2'
	elif 5 <= list_length <= 80:
		group = 'group3'
	else:
		group = 'group4'

	write_log(locus, f"{group}\t{str(time.ctime())}\n")
	return(group)

def decide_order(locus, group, selection, df_Sdis, key_list, method, threads, ### medoid
						label_list,  medoid_list, medoid_assignment):
	if group == 'group1':
		standard_allel = group1(locus, method, threads)
	elif group == 'group2':
		standard_allel = group2(locus, method, threads, label_list, medoid_list, medoid_assignment)
	elif group == 'group3':
		standard_allel = group3(locus, selection, df_Sdis, key_list, method, threads)
	elif group == 'group4':
		standard_allel = group4(locus, selection, df_Sdis, key_list, method, threads, label_list, medoid_list, medoid_assignment)
	print('standard allele:', standard_allel)
	write_log(locus, f"standard allele\t{standard_allel}\n")
	return standard_allel

def get_lpnet_input_size(group, key_list, selection, medoid_list):
	if group == "group1":
		return len(key_list)
	elif group == "group2":
		return len(medoid_list)
	elif group == "group3":
		return len(selection)
	elif group == "group4":
		return len(medoid_list)
	else:
		return ""

def write_locus_processing_summary(locus, summary):
	directory_path = get_filename.dir_path(locus)
	tsv_file = os.path.join(directory_path, f"{locus}_processing_summary.tsv")

	fields = [
		"locus",
		"n_filtered_alleles",
		"n_snp_representatives",
		"group",
		"n_lpnet_input",
		"n_medoid_clusters",
		"standard_allele",
		"tree_method",
		"max_lpnet_taxa",
	]

	row = {field: summary.get(field, "") for field in fields}

	with open(tsv_file, "w", newline="") as f:
		writer = csv.DictWriter(f, fieldnames=fields, delimiter="\t")
		writer.writeheader()
		writer.writerow(row)

def calc_phylocode(locus, rm_temp, method, threads, locus_fasta, max_lpnet_taxa):
	write_log(locus, f"phylocode\tBegin\t{str(time.ctime())}\n")

	selection, df_Sdis, key_list = snps.snp_grouping(locus)
	ss_list = get_filename.ss_list(locus)
	selection_list = list(selection.keys())#selection seq_name list
	with open (ss_list,'w') as ofile:
		ofile.write('\n' .join(selection_list))
	group = get_group(locus)
	directory_path = get_filename.dir_path(locus)
	selected_align = get_filename.selected_align(locus)

	if group == 'group1' or group == 'group2':
		represent_fasta = directory_path + f"/{locus}_represent.fasta"
		fasta_select(locus_fasta, represent_fasta, ss_list) # Write representative alleles fasta
		in_fasta = get_filename.selected_align(locus)
	else: # group == 'group3' or group == 'group4'
		represent_fasta = directory_path + f"/{locus}_represent.fasta"
		fasta_select(locus_fasta, represent_fasta, ss_list) # Write represemtative alleles fasta
		in_fasta = directory_path + f"/{locus}_represent.aln"
		with open(in_fasta, "w") as out_handle:
			subprocess.run(
				["mafft", "--auto", represent_fasta],
				stdout=out_handle,
				check=True,
				text=True
			)

	make_distance_matrix(locus, in_fasta, method, threads) # Make tree and calculate distance matrix
	
	write_log(locus, f"run_lpnet\tBegin\t{str(time.ctime())}\n")
	label_list, medoid_list, medoid_assignment = run_lpnet(locus, group, max_lpnet_taxa) # Run lpnet
	write_log(locus, f"run_lpnet\tEnd\t{str(time.ctime())}\n")

	write_log(locus, f"decide_order\tBegin\t{str(time.ctime())}\n")
	standard_allel = decide_order(locus, group, selection, df_Sdis, key_list, method, threads, ### medoid
						label_list,  medoid_list, medoid_assignment)

	n_lpnet_input = get_lpnet_input_size(
			group,
			key_list,
			selection,
			medoid_list
		)

	summary = {
		"locus": locus,
		"n_filtered_alleles": len(key_list),
		"n_snp_representatives": len(selection),
		"group": group,
		"n_lpnet_input": n_lpnet_input,
		"n_medoid_clusters": len(medoid_assignment) if medoid_assignment else 0,
		"standard_allele": standard_allel,
		"tree_method": method,
		"max_lpnet_taxa": max_lpnet_taxa,
	}

	write_locus_processing_summary(locus, summary)

	write_log(locus, f"decide_order\tEnd\t{str(time.ctime())}\n")

	if rm_temp:
		del_tempfiles(locus)
	
	write_log(locus, f"phylocode\tEnd\t{str(time.ctime())}\n")

